### PR TITLE
docs: add Dutch translation for Code of Conduct

### PR DESCRIPTION
**Pull request by usethetics**
Added slightly modified 1.4 version of the Contributor Covenant Dutch translation of the code of conduct.

Modifications include minor typo fixes.

### CODE REVIEW

**Comment by Robbert** [comment]
@usethetics The English code of conduct we added yesterday was based on v2.0 of the Contributor Covenant, and you added v1.4 of the Dutch code of conduct. Was there no translation available for the latest version?

**Comment by Robbert** [comment]
This PR was created to address nl-design-system/backlog#2.

**Comment by usethetics** [comment]
> @usethetics The English code of conduct we added yesterday was based on v2.0 of the Contributor Covenant, and you added v1.4 of the Dutch code of conduct. Was there no translation available for the latest version?

No, there is unfortunately no version 2.0 currently available from the Contributor Covenant website.

**Review by Robbert — APPROVED** [review]
Thanks, looks good!

I spot two formatting details that will probably be adjusted by [Prettier](http://prettier.io), but we'll get to that later: an empty newline before the first header, and the list items are prefixed with `*` instead of `-`.

**Pull request merged**
